Repository jacek-kurlit/pik, pull requests merged in 2024-09, with the labels that each got.

#66 feat: Quit program with ctrl+c
  README.md
  src/tui.rs
  src/tui/rendering.rs
Labels: enhancement

#67 docs: added tapes to recreate gifs
  .gitignore
  Cargo.lock
  README.md
  docs/search_by_arg.gif
  docs/search_by_arg.tape
  docs/search_by_name.gif
  docs/search_by_name.tape
  docs/search_by_path.gif
  docs/search_by_path.tape
  docs/search_by_port.gif
  docs/search_by_port.tape
  docs/search_everywhere.gif
  docs/search_everywhere.tape
Labels: documentation

#71 Fix infinite scroll in process details area
  src/tui.rs
  src/tui/rendering.rs
Labels: bug

#78 Add cli arguments to configure the viewport size
  src/args.rs
  src/main.rs
  src/tui.rs
Labels: enhancement

#77 Add faster scrolling: jump over 10 lines when pressing PgUp/PgDown.
  src/tui.rs
  src/tui/rendering.rs
Labels: enhancement

#76 Add fuzzy search for Cmd type of queries
  Cargo.lock
  Cargo.toml
  src/processes/filters.rs
  tests/processes_search.rs
Labels: enhancement
