Repository jacek-kurlit/pik, pull requests merged in 2024-10, with the labels that each got.

#82 add supported operating system in readme
  README.md
Labels: documentation

#83 Add fuzzy search for Cmd, Ports, and Args
  src/processes/filters.rs
  tests/processes_search.rs
Labels: enhancement, performance

#86 fixed failing tests - removed fuzzy search from args
  README.md
  src/processes/filters.rs
  tests/processes_search.rs
Labels: bug

#91 add `ctrl+arrow up`/`ctrl+arrow down` keybinding to go first/end row
  README.md
  src/tui.rs
  src/tui/rendering.rs
Labels: enhancement

#92 v 0.9.0
  Cargo.lock
  Cargo.toml
  pik.spec
  src/processes.rs
Labels: chore

#93 Added sorting search results by match score
  src/processes.rs
  src/processes/filters.rs
  tests/processes_search.rs
Labels: enhancement
